import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';

export default function Sobre({ author }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Movies Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Sobre o Movies Nextjs
        </h1>

        O sistema foi feito em live para demonstrar os primeiros passos com o nextjs.

        <hr />
        
        Autor: {author}

        <Link href="/sobre">Sobre</Link>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  return {
    props: {
      author: 'Dieisson Narde'
    }
  }
}